"""Unit tests for scripts/translation_core.py — the shared core behind the
OpenWebUI tool and pipe deployables (generated by scripts/build_deployables.py)."""

import asyncio
import sys
import types
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = PROJECT_ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))


def _stub_requests(monkeypatch):
    stub = types.ModuleType("requests")
    stub.post = None
    monkeypatch.setitem(sys.modules, "requests", stub)
    return stub


@pytest.fixture
def core(monkeypatch):
    _stub_requests(monkeypatch)
    import translation_core

    importlib_reload = __import__("importlib").reload
    return importlib_reload(translation_core)


# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


class TestPureHelpers:
    def test_parse_command_with_pair(self, core):
        assert core.parse_command("/translate en fa hello world") == ("hello world", "en", "fa")

    def test_parse_command_arrow_pair(self, core):
        assert core.parse_command("/translate de->ru gut tag") == ("gut tag", "de", "ru")

    def test_parse_command_body_only(self, core):
        # Two short leading tokens are always read as a language pair
        # ("some"/"words" would be); a non-code word defeats the pair
        # regex and everything after /translate is the body.
        assert core.parse_command("/translate hello_world some text") == ("hello_world some text", None, None)

    def test_parse_command_passthrough(self, core):
        assert core.parse_command("just text") == ("just text", None, None)

    def test_is_referential(self, core):
        assert core.is_referential("translate this")
        assert core.is_referential("ترجمه")
        assert core.is_referential("")
        assert not core.is_referential("translate this whole document about quantum mechanics")

    def test_context_blocks_strips_source_tags(self, core):
        # One block per <context> occurrence (v0.11.3 injects one), inner
        # <source> tags stripped, multiple sources merged.
        text = 'before <context>\n<source id="1" name="a.md">BODY ONE</source>\n<source id="2" name="b.md">BODY TWO</source>\n</context> after'
        assert core.context_blocks(text) == ["BODY ONE\nBODY TWO"]

    def test_current_remainder_strips_instruction_line(self, core):
        t = "Please translate this:\n\nThe actual content that should survive."
        assert core.current_remainder(t, "") == "The actual content that should survive."

    def test_current_remainder_keeps_real_sentences(self, core):
        t = "The moon lands softly on dark soil tonight."
        assert core.current_remainder(t, "") == t

    def test_current_remainder_first_line_instruction_dropped(self, core):
        # Pinned limitation: a single line that merely *starts* with an
        # instruction word is dropped even when it is a full sentence.
        assert core.current_remainder("Translate the moon lands softly.", "") == ""

    def test_strip_wrappers(self, core):
        t = '<attached_files>\n<file id="1"/>\n</attached_files>\nreal text'
        assert core.strip_wrappers(t) == "real text"


class TestSanitize:
    def test_base64_stripped_alt_kept(self, core):
        t = "Intro text\n![diagram](data:image/png;base64,iVBORw0KGgoAAAANS)\nOutro"
        out = core.sanitize_document(t)
        assert "iVBORw0KGgo" not in out
        assert "diagram" in out
        assert "Intro text" in out and "Outro" in out

    def test_html_tags_stripped_inner_kept(self, core):
        out = core.sanitize_document("A <b>bold</b> word <!-- comment --> end")
        assert out == "A bold word end"

    def test_image_only_empty(self, core):
        # Alt text is translatable and deliberately kept; an image with no
        # alt is the true "nothing left" case.
        assert core.sanitize_document("![](data:image/png;base64,AAAA)") == ""


class TestResolveFromMessages:
    def test_system_prompt_never_a_source(self, core):
        messages = [
            {"role": "system", "content": "You are a helpful assistant with secrets."},
            {"role": "user", "content": "translate this"},
        ]
        text, source = core.resolve_from_messages(
            "translate this", messages, 1, "translate this", ""
        )
        assert text == ""
        assert source == ""

    def test_earlier_context_block_wins_over_history(self, core):
        messages = [
            {"role": "user", "content": "here you go"},
            {"role": "user", "content": "<context>\n<source id='1' name='doc.md'>EARLIER DOC</source>\n</context>\ntranslate it"},
            {"role": "assistant", "content": "ok"},
            {"role": "user", "content": "translate this"},
        ]
        text, source = core.resolve_from_messages(
            "translate this", messages, 3, "translate this", ""
        )
        assert text == "EARLIER DOC"
        assert source == "earlier document"

    def test_assistant_history_excluded_when_flagged(self, core):
        # Pipe mode: a previous pipe reply (plain assistant text, no tool
        # calls) must not be picked as the source of "translate this".
        messages = [
            {"role": "user", "content": "The quick brown fox jumps over the lazy dog."},
            {"role": "assistant", "content": "سگ تنبل"},  # previous translation
            {"role": "user", "content": "translate this"},
        ]
        text, source = core.resolve_from_messages(
            "translate this", messages, 2, "translate this", "",
            include_assistant_history=False,
        )
        assert text == "The quick brown fox jumps over the lazy dog."
        assert source == "conversation history"

    def test_tool_mode_relay_indices_skip_relay(self, core):
        messages = [
            {"role": "user", "content": "translate the document"},
            {
                "role": "assistant",
                "content": None,
                "tool_calls": [{"id": "c1", "function": {"name": "translate", "arguments": "{}"}}],
            },
            {"role": "tool", "tool_call_id": "c1", "content": "FULL TRANSLATION BODY"},
            {"role": "assistant", "content": "FULL TRANSLATION BODY"},
            {"role": "user", "content": "translate this"},
        ]
        # tool mode (include assistant history): the relay assistant message
        # is skipped, so no source is found here (the real doc is elsewhere).
        text, _ = core.resolve_from_messages(
            "translate this", messages, 5, "translate this", ""
        )
        assert text == ""
        # but the user's original instruction message has no body either.
        relays = core.translation_relay_indices(messages)
        assert 3 in relays


class TestResolveLanguages:
    def test_explicit_beats_valves(self, core):
        assert core.resolve_languages("en", "fa", {"valves": {"source_lang": "de", "target_lang": "ru"}}, "x", "y") == ("en", "fa")

    def test_dict_valves(self, core):
        assert core.resolve_languages(None, None, {"valves": {"source_lang": "de", "target_lang": "ru"}}, "en", "fa") == ("de", "ru")

    def test_instance_valves_pydantic_v2_shape(self, core):
        # Production shape: OpenWebUI injects a UserValves *instance*
        # (pydantic v2 models are not mappings — `**instance` would fail).
        class Valves:
            source_lang = "de"
            target_lang = "ru"

        assert core.resolve_languages(None, None, {"valves": Valves()}, "en", "fa") == ("de", "ru")

    def test_defaults(self, core):
        assert core.resolve_languages(None, None, {}, "en", "fa") == ("en", "fa")
        assert core.resolve_languages(None, None, None, "en", "fa") == ("en", "fa")


class TestBuildFileName:
    def test_from_source_file(self, core):
        assert core.build_file_name(["paper.md"], "fa") == "paper.translated.fa.md"

    def test_fallback_name(self, core):
        assert core.build_file_name([], "fa") == "translation-fa.md"

    def test_url_names_ignored(self, core):
        assert core.build_file_name(["https://x/y.md"], "fa") == "translation-fa.md"


# ---------------------------------------------------------------------------
# TranslationClient (stubbed requests)
# ---------------------------------------------------------------------------


class _Resp:
    def __init__(self, status_code, payload=None, text=""):
        self.status_code = status_code
        self._payload = payload or {}
        self.text = text

    def json(self):
        return self._payload


class TestTranslationClient:
    def test_gateway_success(self, core, monkeypatch):
        calls = []

        def fake_post(url, json=None, timeout=None):
            calls.append((url, json, timeout))
            return _Resp(200, {"translation": "TARJOMEH"})

        core.requests.post = fake_post
        client = core.TranslationClient(
            backend_mode="gateway",
            gateway_url="http://gw/translate",
            max_new_tokens=512,
            timeout_seconds=60,
        )
        out = client.translate("hello", "en", "fa", True)
        assert out == "TARJOMEH"
        url, payload, timeout = calls[0]
        assert url == "http://gw/translate"
        assert payload == {
            "text": "hello",
            "source_lang": "en",
            "target_lang": "fa",
            "max_new_tokens": 512,
            "split_sentences": True,
        }
        assert timeout == 60

    def test_gateway_error_string(self, core, monkeypatch):
        def fake_post(url, json=None, timeout=None):
            return _Resp(502, text="upstream is down")

        core.requests.post = fake_post
        client = core.TranslationClient(backend_mode="gateway")
        out = client.translate("hello", "en", "fa", True)
        assert out.startswith("Gateway Error (502):")

    def test_vllm_mode_payload(self, core, monkeypatch):
        calls = []

        def fake_post(url, json=None, timeout=None):
            calls.append((url, json))
            return _Resp(200, {"choices": [{"message": {"content": "FA"}}]})

        core.requests.post = fake_post
        client = core.TranslationClient(
            backend_mode="vllm",
            vllm_url="http://vllm/v1/chat/completions",
            vllm_model_name="mt",
            max_new_tokens=256,
        )
        out = client.translate("hello", "en", "fa", False)
        assert out == "FA"
        url, payload = calls[0]
        assert url == "http://vllm/v1/chat/completions"
        assert payload["model"] == "mt"
        assert payload["stop_token_ids"] == [1, 106]
        assert payload["temperature"] == 0.0
        assert payload["messages"][0]["content"][0]["text"] == "hello"

    def test_vllm_error_string(self, core, monkeypatch):
        def fake_post(url, json=None, timeout=None):
            return _Resp(400, text="prompt too long")

        core.requests.post = fake_post
        client = core.TranslationClient(backend_mode="vllm")
        out = client.translate("hello", "en", "fa", False)
        assert out.startswith("vLLM Error (400):")


# ---------------------------------------------------------------------------
# resolve_source end to end (async, no open_webui needed)
# ---------------------------------------------------------------------------


class TestResolveSource:
    @staticmethod
    def _run(coro):
        loop = asyncio.new_event_loop()
        try:
            return loop.run_until_complete(coro)
        finally:
            loop.close()

    def test_explicit_text_wins(self, core):
        info = self._run(core.resolve_source("A real document body here to translate.", [], []))
        assert info["text"] == "A real document body here to translate."
        assert info["source"] == "provided text"

    def test_referential_goes_to_messages(self, core):
        messages = [
            {"role": "user", "content": [{"type": "text", "text": "<context>\n<source id='1' name='d.md'>DOC BODY</source>\n</context>\ntranslate this"}]},
        ]
        info = self._run(core.resolve_source("translate this", messages, []))
        assert info["text"] == "DOC BODY"
        assert info["source"] == "document context"

    def test_command_languages_extracted(self, core):
        info = self._run(core.resolve_source("/translate en de some words to translate", [], []))
        assert info["cmd_src"] == "en"
        assert info["cmd_tgt"] == "de"
        assert info["text"] == "some words to translate"

    def test_pasted_text_message(self, core):
        # Pipe shape: no argument, the user message IS the content.
        messages = [
            {"role": "user", "content": [{"type": "text", "text": "The quick brown fox jumps over the lazy dog."}]},
        ]
        info = self._run(core.resolve_source("", messages, []))
        assert info["text"] == "The quick brown fox jumps over the lazy dog."
        assert info["source"] == "message text"
