"""
title: TranslateGemma Translation Pipe (Deterministic)
author: TranslateGemma Team
description: Select this pipe as the model and every message becomes a translation request. Files, pasted text, and references like "translate this" are resolved deterministically, the document never touches a chat LLM (no context overflow, no chatty replies, nothing re-emitted), the full structured translation is streamed back as the reply, and it is attached as a downloadable file.
version: 1.0.1
license: MIT
requirements: requests, pydantic
"""
"""Shared core for the OpenWebUI translation front ends.

This module holds everything the OpenWebUI *tool* and the *pipe* have in
common: deterministic source resolution (files, context blocks, message
text, history — never the system prompt), OCR artifact sanitization, the
gateway/vLLM call, and the downloadable-file delivery (OpenWebUI file
storage + chat attachment). It is the canonical implementation; the two
deployables are single self-contained files (OpenWebUI execs them as
standalone modules, so they cannot import this file) and are generated by
scripts/build_deployables.py, which inlines this source into each front end.

Imports `requests` at module level (a declared requirement of both
deployables) and only touches `open_webui.*` lazily inside functions, so it
also runs in a plain test environment.
"""

import asyncio
import base64
import os
import re

import requests

__all__ = [
    "TEXT_LIKE_EXT",
    "TranslationClient",
    "attached_file_ids",
    "context_blocks",
    "current_remainder",
    "file_text",
    "file_text_by_id",
    "is_referential",
    "last_user_message",
    "msg_text",
    "parse_command",
    "resolve_languages",
    "resolve_source",
    "sanitize_document",
    "store_translation_file",
    "strip_wrappers",
    "translation_relay_indices",
    "upload_translation_file",
]

TEXT_LIKE_EXT = (
    ".md", ".markdown", ".txt", ".text", ".csv", ".tsv", ".json", ".html",
    ".htm", ".xml", ".rst", ".yaml", ".yml", ".ini", ".log",
)
_MAX_RAW_READ_BYTES = 20 * 1024 * 1024

# Non-translatable artifacts. OCR-generated markdown (pymupdf4llm, docling,
# tesseract post-processing) routinely embeds full base64 image payloads
# inline. Sent to the MT model they are "translated" into garbage, blow the
# token count up by orders of magnitude, and the inflated translation then
# overflows the base model's context on the way back. Stripped before the
# gateway call, in the tool that knows it is handling documents.
_DATA_URI_RE = re.compile(r"data:[A-Za-z0-9/+.=-]+;base64,[A-Za-z0-9+/=\s]+")
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\([^)]*\)")
_HTML_TAG_RE = re.compile(r"</?[A-Za-z][^>]*>")
_BLANK_RUN_RE = re.compile(r"\n{3,}")
# Collapse the space runs left where tags/blobs were stripped, without
# touching line-start indentation (code blocks).
_SPACE_RUN_RE = re.compile(r"(?<=\S)[ \t]{2,}(?=\S)")

_REFERENTIAL = {
    "",
    "this",
    "that",
    "it",
    "these",
    "those",
    "above",
    "the above",
    "the above message",
    "the above text",
    "the text",
    "this text",
    "that text",
    "previous",
    "previous message",
    "this file",
    "that file",
    "the file",
    "attached file",
    "the document",
    "this document",
    "translate",
    "translate this",
    "translate that",
    "translate it",
    "translate the above",
    "translate the above message",
    "translate the above text",
    "translate the text",
    "translate this text",
    "translate previous",
    "translate previous message",
    "translate this file",
    "translate that file",
    "translate the file",
    "translate file",
    "translate the document",
    "translate this document",
    "ترجمه",
    "ترجمه کن",
    "این را ترجمه کن",
    "متن بالا را ترجمه کن",
    "بالا را ترجمه کن",
    "این متن را ترجمه کن",
    "این فایل را ترجمه کن",
    "فایل را ترجمه کن",
    "متن را ترجمه کن",
    "متن بالا",
}

_REFERENCE_PREFIXES = (
    "translate this",
    "translate that",
    "translate the above",
    "translate the text",
    "translate file",
    "translate the file",
    "translate the document",
    "translate previous",
    "translate attached",
)

_INSTRUCTION_LINE_RE = re.compile(
    r"^(please\s+)?(translate|convert|translate the following|traduis|übersetze|ترجمه)",
    re.IGNORECASE,
)


# ------------------------------------------------------------ message utils


def msg_text(message: dict) -> str:
    """Message content as text, for both plain strings and content-part lists."""
    content = message.get("content", "")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = [
            str(part.get("text") or "")
            for part in content
            if isinstance(part, dict) and part.get("type") == "text"
        ]
        return "\n".join(parts)
    return ""


def last_user_message(messages) -> tuple:
    """(index, text) of the most recent user message, or (-1, '')."""
    if not messages:
        return -1, ""
    for i in range(len(messages) - 1, -1, -1):
        msg = messages[i]
        if isinstance(msg, dict) and msg.get("role") == "user":
            return i, msg_text(msg)
    return -1, ""


def context_blocks(text: str) -> list:
    """All OpenWebUI RAG context blocks in `text`, inner <source> tags stripped."""
    blocks = []
    for m in re.finditer(r"<context>(.*?)</context>", text or "", re.DOTALL):
        inner = re.sub(r"</?source[^>]*>", "", m.group(1))
        inner = inner.strip()
        if inner:
            blocks.append(inner)
    return blocks


def strip_wrappers(text: str) -> str:
    """Remove file-tag wrappers an LLM may have copied verbatim into `text`."""
    text = re.sub(r"<attached_files>.*?</attached_files>", "", text or "", flags=re.DOTALL)
    text = re.sub(r"<knowledge>.*?</knowledge>", "", text, flags=re.DOTALL)
    return text.strip()


def attached_file_ids(text: str) -> list:
    ids = []
    for m in re.finditer(r"<file\b[^>]*?/?>", text or ""):
        idm = re.search(r'id="([^"]+)"', m.group(0))
        if idm:
            ids.append(idm.group(1))
    return ids


def is_referential(text: str) -> bool:
    clean = (text or "").strip().lower()
    if clean in _REFERENTIAL:
        return True
    # Prefix matches count only for short phrases: an explicitly passed
    # long argument is content, even one starting with "translate this".
    return any(clean.startswith(prefix) for prefix in _REFERENCE_PREFIXES) and len(clean) < 30


def parse_command(text: str) -> tuple:
    """Split a /translate command into (body, source_lang, target_lang)."""
    clean = (text or "").strip()
    m = re.match(
        r"^/translate\s+([a-zA-Z]{2,5}(?:-[a-zA-Z0-9]+)?)"
        r"(?:->|:|\s+)"
        r"([a-zA-Z]{2,5}(?:-[a-zA-Z0-9]+)?)\s+(.+)$",
        clean,
        re.DOTALL | re.IGNORECASE,
    )
    if m:
        return m.group(3).strip(), m.group(1).lower(), m.group(2).lower()
    m = re.match(r"^/translate\s+(.+)$", clean, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip(), None, None
    return clean, None, None


def current_remainder(current_text: str, reference: str) -> str:
    """Text carried by the current user message beyond the reference/instruction."""
    t = current_text or ""
    t = re.sub(r"<attached_files>.*?</attached_files>", "", t, flags=re.DOTALL)
    t = re.sub(r"<context>.*?</context>", "", t, flags=re.DOTALL)
    t = re.sub(r"<knowledge>.*?</knowledge>", "", t, flags=re.DOTALL)

    kept = []
    for line in t.splitlines():
        s = line.strip()
        if (
            not kept
            and s
            and len(s) < 120
            and _INSTRUCTION_LINE_RE.match(s)
        ):
            continue
        kept.append(line)
    t = "\n".join(kept).strip()

    ref = (reference or "").strip()
    if ref and t == ref:
        t = ""
    elif ref and ref.isascii() and len(t) > len(ref):
        # trailing "translate this" style addendum (ASCII refs only:
        # whitespace token boundaries do not exist in e.g. Persian)
        t = re.sub(re.escape(ref) + r"[\s,:：]*$", "", t, flags=re.IGNORECASE).strip()

    if not t or is_referential(t):
        return ""
    return t if len(t) >= 8 else ""


def translation_relay_indices(messages: list) -> set:
    """Indices of assistant messages that merely relay a `translate` tool result.

    Those are translations, not sources: falling back onto them would
    translate the previous translation.
    """
    translate_call_ids = set()
    for msg in messages:
        if not isinstance(msg, dict) or msg.get("role") != "assistant":
            continue
        for tc in msg.get("tool_calls") or []:
            fn = (tc.get("function") or {}).get("name", "")
            if fn == "translate" and tc.get("id"):
                translate_call_ids.add(tc.get("id"))
    if not translate_call_ids:
        return set()
    relays = set()
    for i, msg in enumerate(messages):
        if isinstance(msg, dict) and msg.get("role") == "tool" and msg.get("tool_call_id") in translate_call_ids:
            for j in range(i + 1, len(messages)):
                if messages[j].get("role") == "assistant":
                    relays.add(j)
                    break
    return relays


# ------------------------------------------------------------------ resolve


def resolve_from_messages(
    clean: str,
    messages,
    current_idx: int,
    current_text: str,
    attached_text: str,
    include_assistant_history: bool = True,
) -> tuple:
    """Deterministic resolution of the text to translate.

    Returns (text, source) where source labels where the text came from.
    Order: current message context block -> attached-file text ->
    current message remainder -> earlier context blocks -> last
    substantive history message. Never returns the system prompt, tool
    results, or a prior `translate` relay as a source.

    `include_assistant_history=False` (the pipe's mode): the history
    fallback then only scans earlier USER messages. Pipe replies are plain
    assistant messages with no tool-call marker to identify them, so
    including assistant text would let "translate this" latch onto the
    previous translation and re-translate it.
    """
    if messages:
        ctx = context_blocks(current_text)
        if ctx:
            return ctx[-1], "document context"

    if attached_text.strip():
        return attached_text.strip(), "attached file"

    remainder = current_remainder(current_text, clean)
    if remainder:
        return remainder, "message text"

    if messages:
        limit = current_idx if current_idx >= 0 else len(messages)
        earlier = []
        for msg in messages[:limit]:
            if isinstance(msg, dict) and msg.get("role") == "user":
                earlier.extend(context_blocks(msg_text(msg)))
        if earlier:
            return earlier[-1], "earlier document"

        relays = translation_relay_indices(messages)
        for i in range(len(messages) - 1, -1, -1):
            msg = messages[i]
            if not isinstance(msg, dict):
                continue
            if i == current_idx or i in relays:
                continue
            role = msg.get("role")
            # System/developer prompts are instructions, not sources:
            # falling back onto one is how a chat ends up "translating"
            # the system prompt.
            if role in ("system", "developer", "function", "tool"):
                continue
            if role == "assistant" and (
                not include_assistant_history or msg.get("tool_calls")
            ):
                continue
            content = msg_text(msg).strip()
            content = re.sub(
                r"<attached_files>.*?</attached_files>", "", content, flags=re.DOTALL
            ).strip()
            content = re.sub(
                r"<context>.*?</context>", "", content, flags=re.DOTALL
            ).strip()
            if not content:
                continue
            if content.startswith("/translate"):
                continue
            # Referential-only messages ("translate this") carry no source;
            # messages that carry a source alongside the reference do.
            remainder = current_remainder(content, "")
            if not remainder:
                continue
            return remainder, "conversation history"
    return "", ""


async def resolve_source(text_arg: str, messages, files, include_assistant_history: bool = True) -> dict:
    """The full source-resolution pipeline shared by the tool and the pipe.

    `text_arg` is the tool's `text` argument, or "" for the pipe (which
    always resolves from the conversation itself). Returns a dict with
    'text', 'source', 'file_names', 'unreadable_files', 'cmd_src',
    'cmd_tgt'.
    """
    # 1. Attached files on the CURRENT message (full text, no viewer caps).
    file_parts = []
    file_names = []
    unreadable_files = []
    for item in files or []:
        if not isinstance(item, dict):
            continue
        if item.get("type") is not None and item.get("type") not in ("file", "doc", "text", "note"):
            continue
        ft = await file_text(item)
        label = str(item.get("name") or item.get("id") or "attached file")
        if ft and ft.strip():
            file_parts.append(ft.strip())
            file_names.append(label)
        else:
            unreadable_files.append(label)
    attached_text = "\n\n".join(file_parts)

    # 2. Parse /translate command for language overrides.
    clean, cmd_src, cmd_tgt = parse_command(text_arg)

    # 3. Resolve the text. An explicit non-referential `text` wins, unless
    #    it is the model dumping the whole message (then mine the context).
    if not is_referential(clean) and clean:
        ctx = context_blocks(clean)
        clean = strip_wrappers(clean)
        resolved = ctx[-1] if ctx else clean
        source = "document context" if ctx else "provided text"
        if not ctx:
            # Prompt-modal templates wrap the text in a short instruction
            # line; strip it only when the body is blank-line-separated,
            # so a real sentence that happens to start with "translate"
            # is never touched.
            m = re.match(r"^([^\n]{0,119})\n\n(.+)$", resolved, re.DOTALL)
            if m and _INSTRUCTION_LINE_RE.match(m.group(1).strip()):
                resolved = m.group(2)
        if not resolved.strip() and attached_text.strip():
            resolved, source = attached_text, "attached file"
    else:
        current_idx, current_text = last_user_message(messages)
        # attached-file ids referenced in the current message
        if not attached_text.strip():
            ids = attached_file_ids(current_text)
            fetched = []
            for fid in ids:
                t = await file_text_by_id(fid)
                if t and t.strip():
                    fetched.append(t.strip())
                else:
                    unreadable_files.append(fid)
            if fetched:
                attached_text = "\n\n".join(fetched)
        resolved, source = resolve_from_messages(
            clean,
            messages,
            current_idx,
            current_text,
            attached_text,
            include_assistant_history=include_assistant_history,
        )

    return {
        "text": (resolved or "").strip(),
        "source": source,
        "file_names": file_names,
        "unreadable_files": unreadable_files,
        "cmd_src": cmd_src,
        "cmd_tgt": cmd_tgt,
    }


# --------------------------------------------------------------- sanitise


def sanitize_document(text: str) -> str:
    """Remove non-translatable artifacts from a document before translation.

    Order matters: data URIs first (they can contain anything, including
    angle brackets that would confuse the tag stripping), then markdown
    images (keeping the alt text, which *is* translatable), then HTML
    comments and tags (keeping inner text). Collapses blank runs. Returns
    the cleaned text; may be empty when the input was only images/binary.
    """
    if not text:
        return ""
    text = _DATA_URI_RE.sub(" ", text)
    text = _MD_IMAGE_RE.sub(lambda m: m.group(1).strip(), text)
    text = _HTML_COMMENT_RE.sub(" ", text)
    text = _HTML_TAG_RE.sub(" ", text)
    text = _BLANK_RUN_RE.sub("\n\n", text)
    text = _SPACE_RUN_RE.sub(" ", text)
    return text.strip()


# ------------------------------------------------------------ file text


async def file_record(file_id: str):
    try:
        from open_webui.models.files import Files

        return await Files.get_file_by_id(str(file_id))
    except Exception:
        return None


def _read_bytes(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()


async def raw_disk_text(record) -> str:
    """Naive text read for text-like files whose extraction is pending or failed.

    The raw upload bytes are on disk as soon as the upload completes, so
    this keeps .md/.txt usable even when the extraction pipeline has not
    written ``data.content`` yet (or failed on it). Binary formats are
    left alone: guessing at a PDF byte stream is worse than an honest error.
    """
    try:
        name = str(getattr(record, "filename", "") or "")
        meta = getattr(record, "meta", None)
        content_type = str(meta.get("content_type") or "") if isinstance(meta, dict) else ""
        text_like = name.lower().endswith(TEXT_LIKE_EXT) or "text/" in content_type
        if not text_like:
            return ""
        rel_path = getattr(record, "path", None)
        if not rel_path:
            return ""
        from open_webui.storage.provider import Storage

        abs_path = await asyncio.to_thread(Storage.get_file, rel_path)
        if not abs_path or not os.path.isfile(abs_path):
            return ""
        if os.path.getsize(abs_path) > _MAX_RAW_READ_BYTES:
            return ""
        raw = await asyncio.to_thread(_read_bytes, abs_path)
        for enc in ("utf-8-sig", "utf-8", "latin-1"):
            try:
                text = raw.decode(enc)
                break
            except UnicodeDecodeError:
                continue
        else:
            return ""
        if "\x00" in text[:4096]:
            return ""
        return text.strip()
    except Exception:
        return ""


def record_content(record) -> str:
    if record is not None:
        data = getattr(record, "data", None)
        if isinstance(data, dict) and data.get("content"):
            return str(data["content"])
    return ""


async def file_text(item: dict) -> str:
    """Full extracted text of one attached-file item, no viewer char caps."""
    if not isinstance(item, dict):
        return ""
    file_obj = item.get("file")
    if isinstance(file_obj, dict):
        data = file_obj.get("data")
        if isinstance(data, dict) and data.get("content"):
            return str(data["content"])
    file_id = item.get("id") or item.get("url")
    if not file_id or str(file_id).startswith(("http://", "https://", "data:")):
        return ""
    record = await file_record(str(file_id))
    content = record_content(record)
    if content:
        return content
    return await raw_disk_text(record)


async def file_text_by_id(file_id: str) -> str:
    record = await file_record(file_id)
    content = record_content(record)
    if content:
        return content
    return await raw_disk_text(record)


# ------------------------------------------------------------- languages


def resolve_languages(source_lang, target_lang, user, default_src, default_tgt) -> tuple:
    """explicit args > user valves > system defaults, all lowercased.

    `user['valves']` arrives as a dict in tests and as an instance of the
    front end's UserValves class in production (OpenWebUI builds it with
    `module.UserValves(**stored)`), so both shapes are read defensively —
    pydantic v2 models are not mappings, and `**instance` would silently
    drop the user's valves.
    """
    src = (source_lang or "").strip().lower()
    tgt = (target_lang or "").strip().lower()

    user_valves = user.get("valves") if isinstance(user, dict) else None

    def _valve(name: str) -> str:
        if user_valves is None:
            return ""
        if isinstance(user_valves, dict):
            return str(user_valves.get(name) or "")
        return str(getattr(user_valves, name, "") or "")

    if not src:
        src = _valve("source_lang").strip().lower()
    if not tgt:
        tgt = _valve("target_lang").strip().lower()

    if not src:
        src = (default_src or "").strip().lower()
    if not tgt:
        tgt = (default_tgt or "").strip().lower()
    return src, tgt


# ----------------------------------------------------------------- client


class TranslationClient:
    """The gateway (or direct vLLM) call. Synchronous: the caller decides
    whether to run it in the event loop or a worker thread."""

    def __init__(
        self,
        backend_mode: str = "gateway",
        gateway_url: str = "http://translategemma-api:8000/translate",
        vllm_url: str = "http://translategemma-vllm:8000/v1/chat/completions",
        vllm_model_name: str = "model",
        max_new_tokens: int = 512,
        timeout_seconds: int = 300,
    ):
        self.backend_mode = backend_mode
        self.gateway_url = gateway_url
        self.vllm_url = vllm_url
        self.vllm_model_name = vllm_model_name
        self.max_new_tokens = max_new_tokens
        self.timeout_seconds = timeout_seconds

    def translate(self, text: str, src: str, tgt: str, split_sentences: bool) -> str:
        """One translation. Returns the text, or an 'Error'/'Gateway
        Error'/'vLLM Error' string on failure — the caller decides what to
        do with errors (never attach a file for them)."""
        if self.backend_mode == "gateway":
            payload = {
                "text": text,
                "source_lang": src,
                "target_lang": tgt,
                "max_new_tokens": self.max_new_tokens,
                "split_sentences": split_sentences,
            }
            resp = requests.post(
                self.gateway_url,
                json=payload,
                timeout=self.timeout_seconds,
            )
            if resp.status_code != 200:
                return f"Gateway Error ({resp.status_code}): {resp.text}"
            return resp.json().get("translation", "")
        payload = {
            "model": self.vllm_model_name,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "source_lang_code": src,
                            "target_lang_code": tgt,
                            "text": text,
                        }
                    ],
                }
            ],
            "temperature": 0.0,
            "top_p": 1.0,
            "max_tokens": self.max_new_tokens,
            "stop_token_ids": [1, 106],
        }
        resp = requests.post(
            self.vllm_url,
            json=payload,
            timeout=self.timeout_seconds,
        )
        if resp.status_code != 200:
            return f"vLLM Error ({resp.status_code}): {resp.text}"
        choices = resp.json().get("choices", [])
        return (
            choices[0].get("message", {}).get("content", "")
            if choices
            else "No translation returned."
        )


# ------------------------------------------------------------ attachments


def build_file_name(file_names: list, tgt: str) -> str:
    name = f"translation-{tgt}.md"
    if file_names:
        base = str(file_names[0]).rsplit(".", 1)[0]
        if base and not base.startswith(("http", "data:")):
            name = f"{base}.translated.{tgt}.md"
    return name


async def upload_translation_file(translation: str, name: str, user_id: str):
    """Store the translation in OpenWebUI's own file storage.

    Returns the FileModel record, or None when storage is unavailable
    (the caller then falls back to a content-only attachment). No RAG
    processing happens — the translation is never embedded into any
    knowledge collection, it is a plain downloadable file.
    """
    try:
        import io
        import uuid

        from open_webui.models.files import FileForm, Files
        from open_webui.storage.provider import Storage
    except Exception:
        return None
    try:
        file_id = str(uuid.uuid4())
        tags = {
            "OpenWebUI-User-Id": str(user_id),
            "OpenWebUI-File-Id": file_id,
        }
        contents, file_path = await asyncio.to_thread(
            Storage.upload_file,
            io.BytesIO(translation.encode("utf-8")),
            f"{file_id}_{name}",
            tags,
        )
        return await Files.insert_new_file(
            str(user_id),
            FileForm(
                id=file_id,
                filename=name,
                path=file_path,
                data={"content": translation, "status": "completed"},
                meta={
                    "name": name,
                    "content_type": "text/markdown",
                    "size": len(contents),
                    "data": {},
                },
            ),
        )
    except Exception:
        return None


async def store_translation_file(
    translation: str,
    file_names: list,
    tgt: str,
    chat_id,
    message_id,
    event_emitter,
    user,
) -> str:
    """Store the translation as a downloadable chat file. Returns the name.

    When possible the translation is stored as a real OpenWebUI file
    (file storage + DB record): the chat chip's modal then previews the
    markdown and the file name is a link to /files/{id}/content, which
    the browser downloads. Without storage access it degrades to a
    content-only entry (preview only). Persistence and the
    chat:message:files event are best effort — a failure here must not
    fail the translation itself.
    """
    name = build_file_name(file_names, tgt)

    user_id = str((user or {}).get("id") or "")
    record = await upload_translation_file(translation, name, user_id) if user_id else None

    file_entry = {
        "type": "file",
        "name": name,
        "content_type": "text/markdown",
        "size": len(translation.encode("utf-8")),
    }
    if record is not None:
        # url is the file id: FileItem/FileItemModal resolve
        # /files/{id}/content (Content-Disposition: attachment for
        # non-text/plain types -> the browser downloads the file).
        file_entry["id"] = record.id
        file_entry["url"] = record.id
        file_entry["file"] = record.model_dump()
    else:
        encoded = base64.b64encode(translation.encode("utf-8")).decode("ascii")
        file_entry["url"] = f"data:text/markdown;charset=utf-8;base64,{encoded}"
        file_entry["content"] = translation

    # Persist the attachment to the chat message so it survives reloads.
    # Best effort: a failure here must not fail the translation itself.
    chat_id = str(chat_id or "")
    if (
        chat_id
        and str(message_id)
        and not chat_id.startswith(("temp:", "channel:"))
    ):
        try:
            from open_webui.models.chats import Chats

            saved = await Chats.add_message_files_by_id_and_message_id(
                chat_id, str(message_id), [file_entry]
            )
            if saved:
                file_entry = saved[0]
        except Exception:
            pass

    if event_emitter:
        try:
            await event_emitter(
                {"type": "chat:message:files", "data": {"files": [file_entry]}}
            )
        except Exception:
            pass

    return name

import asyncio
from typing import Any, Callable, Optional
from pydantic import BaseModel, Field

# Reply chunks for streaming: paragraph-sized, so the chat renders
# progressively without fragmenting a line.
_CHUNK_CHARS = 1500


def _reply_chunks(text: str):
    """Yield streaming chunks that rejoin to `text` exactly.

    The framework emits each yielded line as its own delta and never joins
    them back together, so paragraph breaks must ride on the chunk — a
    splitter that drops the separator would flatten the whole document.
    """
    parts = (text or "").split("\n\n")
    for i, part in enumerate(parts):
        sep = "" if i == len(parts) - 1 else "\n\n"
        if part:
            for start in range(0, len(part), _CHUNK_CHARS):
                piece = part[start : start + _CHUNK_CHARS]
                yield piece + sep if start + _CHUNK_CHARS >= len(part) else piece
        elif sep:
            yield sep


class Pipe:
    class Valves(BaseModel):
        BACKEND_MODE: str = Field(
            default="gateway",
            description="Backend mode: 'gateway' (translategemma-api gateway) or 'vllm'",
        )
        GATEWAY_URL: str = Field(
            default="http://translategemma-api:8000/translate",
            description="URL to the TranslateGemma FastAPI gateway (/translate)",
        )
        VLLM_URL: str = Field(
            default="http://translategemma-vllm:8000/v1/chat/completions",
            description="URL to vLLM chat completions if querying vLLM directly",
        )
        VLLM_MODEL_NAME: str = Field(
            default="model",
            description="Model identifier served by vLLM",
        )
        DEFAULT_SOURCE_LANG: str = Field(
            default="en",
            description="Default source language ISO code (e.g. en, fa, de, fr, ru)",
        )
        DEFAULT_TARGET_LANG: str = Field(
            default="fa",
            description="Default target language ISO code (e.g. fa, en, de, fr, ru)",
        )
        MAX_NEW_TOKENS: int = Field(
            default=512,
            description="Maximum new tokens per segment (512 is the gateway default and 4x less KV-cache pressure than 2048 on long documents)",
        )
        TIMEOUT_SECONDS: int = Field(
            default=300,
            description="Timeout in seconds for long documents",
        )
        ATTACH_FILE: bool = Field(
            default=True,
            description=(
                "Attach the translation as a downloadable chat file (stored in "
                "OpenWebUI file storage). The full translation is always part "
                "of the reply itself; the file is a convenience copy."
            ),
        )

    class UserValves(BaseModel):
        source_lang: str = Field(
            default="",
            description="Personal default source language code (leave blank for system default)",
        )
        target_lang: str = Field(
            default="",
            description="Personal default target language code (leave blank for system default)",
        )

    def __init__(self):
        self.valves = self.Valves()

    async def pipe(
        self,
        body: dict,
        __user__: Optional[dict] = None,
        __chat_id__: Optional[str] = None,
        __message_id__: Optional[str] = None,
        __files__: Optional[list] = None,
        __event_emitter__: Optional[Callable[[dict], Any]] = None,
    ):
        """Handle one chat completion. The body's messages are the
        conversation; the reply IS the translation. No base model is
        involved at any point."""
        body = body or {}
        messages = body.get("messages") or []
        stream = bool(body.get("stream", False))

        current_idx, current_text = last_user_message(messages)
        # /translate [src] [tgt] ... works on the pipe too (language override
        # + optional inline text).
        text_arg = current_text if current_text.strip().startswith("/translate") else ""

        info = await resolve_source(
            text_arg, messages, __files__, include_assistant_history=False
        )
        file_names = info["file_names"]
        resolved = sanitize_document(info["text"])

        if not resolved:
            if info["unreadable_files"]:
                names = ", ".join(info["unreadable_files"][:3])
                error = (
                    f"The attached file ({names}) has no readable text yet. "
                    "Its content extraction may still be running or failed — wait a "
                    "moment and send the message again. For files, use the "
                    "'Using Entire Document' upload mode (Settings → Interface → "
                    "File → Default Upload Mode) so the full text is available."
                )
            else:
                error = (
                    "Nothing to translate. Attach a document or paste the text — "
                    "every message sent to this pipe is a translation request. "
                    "Use '/translate [src] [tgt] ...' to override the languages "
                    f"(defaults: {self.valves.DEFAULT_SOURCE_LANG} → "
                    f"{self.valves.DEFAULT_TARGET_LANG})."
                )
            return error

        src, tgt = resolve_languages(
            info["cmd_src"] or None,
            info["cmd_tgt"] or None,
            __user__,
            self.valves.DEFAULT_SOURCE_LANG,
            self.valves.DEFAULT_TARGET_LANG,
        )
        split = len(resolved) > 250 or "\n" in resolved
        word_count = len(resolved.split())
        source_desc = (
            f"file: {', '.join(file_names[:2])}"
            if info["source"] == "attached file" and file_names
            else info["source"] or "text"
        )

        if __event_emitter__:
            await __event_emitter__(
                {
                    "type": "status",
                    "data": {
                        "description": f"Translating {word_count} words [{src} \u279c {tgt}] (from {source_desc})...",
                        "done": False,
                    },
                }
            )

        client = TranslationClient(
            backend_mode=self.valves.BACKEND_MODE,
            gateway_url=self.valves.GATEWAY_URL,
            vllm_url=self.valves.VLLM_URL,
            vllm_model_name=self.valves.VLLM_MODEL_NAME,
            max_new_tokens=self.valves.MAX_NEW_TOKENS,
            timeout_seconds=self.valves.TIMEOUT_SECONDS,
        )
        try:
            # The gateway call blocks; keep the event loop free for the
            # progress events and other chats.
            result = await asyncio.to_thread(client.translate, resolved, src, tgt, split)
        except Exception as error:
            result = f"Translation connection error: {str(error)}"

        if __event_emitter__:
            await __event_emitter__(
                {
                    "type": "status",
                    "data": {
                        "description": f"Translation complete ({word_count} words).",
                        "done": True,
                    },
                }
            )

        # The client signals failures as prefixed strings; connection
        # problems arrive as "Translation connection error:" (caught above).
        # A failure is not a translation: never attach a file for it.
        is_error = result.startswith(
            ("Error:", "Gateway Error", "vLLM Error", "Translation connection error")
        )
        if is_error:
            return result
        if not result:
            return "The translator returned no text (empty response)."

        if self.valves.ATTACH_FILE:
            await store_translation_file(
                result,
                file_names,
                tgt,
                __chat_id__,
                __message_id__,
                __event_emitter__,
                __user__,
            )

        if stream:
            return _reply_chunks(result)
        return result